# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt install meson ninja-build build-essential
  displayName: 'Install Meson and Ninja'

- script: |
    meson build
    cd build
    ninja || make
  displayName: 'build the project'
